### ISSUE TITLE
nearby POI shows up too late in autocomplete results

### ISSUE THREAD

**Issue by randymeech** [pelias/pelias#271]
I was using the app in the parking lot of an antique store that I added to OSM a while ago. I long-pressed to reverse geocode, so I can see it's in the index:
![2016-02-28 16 28 33](https://cloud.githubusercontent.com/assets/14219/13405152/14b6aae2-deeb-11e5-89e0-aa588cc80408.png)

However, when I type the name of the store, even though I'm right there, I don't see the result:
![2016-02-28 16 28 55](https://cloud.githubusercontent.com/assets/14219/13405183/3a2304c4-deeb-11e5-889d-64eeb2d16388.png)

...I keep going:
![2016-02-28 16 29 20](https://cloud.githubusercontent.com/assets/14219/13405197/4c1e497c-deeb-11e5-83a8-417c33a08f6f.png)

...it finally shows up but after something the next town over:
![2016-02-28 16 29 27](https://cloud.githubusercontent.com/assets/14219/13405206/585743d8-deeb-11e5-91fc-c795832611fe.png)

Since I'm right there at the store, I'd expect this to show up much sooner.

**Comment by missinglink** [comment]
One step ahead of you @randymeech, this issue was addressed in https://github.com/pelias/api/pull/418 and should go live in the next production build.

```
/v1/autocomplete?focus.point.lon=-70.922898&focus.point.lat=41.652889&text=acush

#production
 1)	0 Acushnet Line, Fairhaven, MA
 2)	0 Acush/Nb Line, Acushnet, MA
 3)	0 Acushnet Road 1 & 2, Mattapoisett, MA
 4)	8 Acushnet Avenue, New Bedford, MA
 5)	9 Acushnet Road, Mattapoisett, MA
 6)	Acushnet Quarry, Acushnet, MA
 7)	2 Acushnet Avenue, New Bedford, MA
 8)	6 Acushnet Avenue, New Bedford, MA
 9)	0 Acushnet/Rochester Line, Acushnet, MA
10)	Acushnet Cemetery, Acushnet, MA

#dev
 1)	Acushnet, Acushnet Center, MA
 2)	Acushnet Center, Acushnet, MA
 3)	Acushnet River, New Bedford, MA
 4)	Acushnet Quarry, Acushnet, Massachusetts
 5)	Acushnet Sawmill, Acushnet, Massachusetts
 6)	Acushnet Cemetery, Acushnet, Massachusetts
 7)	Acushnet Cemetery, Acushnet, MA
 8)	Acushnet River Antiques Showroom, New Bedford, Massachusetts     <--
 9)	Acushnet River Seaplane Base, Fairhaven, MA
10)	Acushnet River Seaplane Base, Fairhaven, Massachusetts
```

**Comment by randymeech** [comment]
Awesome thanks -- removing those results is a big help. My other question is about the order given that I was right at the location of result 8 -- shouldn't it show up first?

**Comment by dianashk** [comment]
@randymeech, the order is still a problem. @missinglink and I just discussed a simple fix to address the order. We'll try to have something to test early next week.

**Comment by missinglink** [comment]
It's a complex problem, it's due to the frequency of those terms. We are investigating disabling TF/IDF altogether and some other options for resolving this in our [Q1 milestone](https://github.com/pelias/pelias/milestones/Autocomplete%20Improvements), I'm going to add this issue in to that milestone.

The antiques store should show up around second in the list for "acush", the region should come up first, otherwise a search for 'London' (the city) would be drowned out when there were 10+ "London Drycleaners", "London Dog Groomers" etc. in the general area.

I expect that for the query `/v1/autocomplete?focus.point.lon=-70.922898&focus.point.lat=41.652889&text=antiques` that `Acushnet River Antiques Showroom` should come first in the list; which it isn't, so I'll look in to that at the same time.

**Comment by missinglink** [comment]
this has been fixed in production

```
/v1/autocomplete?focus.point.lon=-70.922898&focus.point.lat=41.652889&text=acush

 1)	Acushnet River Antiques Showroom, New Bedford, MA, USA
 2)	856 Acushnet Avenue, New Bedford, MA, USA
 3)	854 Acushnet Avenue, New Bedford, MA, USA
 4)	844 Acushnet Avenue, New Bedford, MA, USA
 5)	1104 Acushnet Avenue, New Bedford, MA, USA
 6)	1112 Acushnet Avenue, New Bedford, MA, USA
 7)	1118 Acushnet Avenue, New Bedford, MA, USA
 8)	1128 Acushnet Avenue, New Bedford, MA, USA
 9)	1103 Acushnet Avenue, New Bedford, MA, USA
10)	1136 Acushnet Avenue, New Bedford, MA, USA
```

```
/v1/autocomplete?focus.point.lon=-70.922898&focus.point.lat=41.652889&text=antiq

 1)	Acushnet River Antiques Showroom, New Bedford, MA, USA
 2)	Antiquarian House, Plymouth, MA, USA
 3)	Cotuit Antiques, Barnstable Town, MA, USA
 4)	46 Antique Road, South Kingstown, RI, USA
 5)	18 Antique Road, South Kingstown, RI, USA
 6)	8 Antique Road, South Kingstown, RI, USA
 7)	Abagail Adams Antiques, Weymouth Town, MA, USA
 8)	Bridge Antiques, Weymouth Town, MA, USA
 9)	Cobwebs Antiques & Jewelry, Boston, MA, USA
10)	Lilli's Antique Emporium, Brewster, MA, USA
```

**Comment by missinglink** [comment]
added acceptance tests:

```
> ./node_modules/pelias-fuzzy-tester/bin/fuzzy-tester "-e" "prod" "test_cases/autocomplete_acushnet_antiques.json"

Tests completed: 4/4 (retries: 0)
Tests for: http://pelias.mapzen.com/v1 (prod)

autocomplete acushnet antiques
  ✔ [1] "{"focus.point.lat":"41.652889","focus.point.lon":"-70.922898","text":"acus"}"
  ✔ [2] "{"focus.point.lat":"41.652889","focus.point.lon":"-70.922898","text":"antiq"}"
  ✔ [3] "{"focus.point.lat":"41.652889","focus.point.lon":"-70.922898","text":"antique"}"
  ✔ [4] "{"text":"acushnet an"}"
```
