### ISSUE TITLE
Unable to import openaddresses .csv with using --admin-values

### ISSUE THREAD

**Issue by brianjcollins** [pelias/pelias#344]
On my test server, I'm unable to import any openaddresses files with --admin-values.  It imports fine, if I omit --admin-values, however the records are less the values that are needed.  When using admin lookup It never seems to complete, nor does the elasticsearch count increase.  It went for 5 hours just repeating `'Number of bad records: 0'` The error log shows what appears to be the problem, but I'm unsure what it is.  Something to do with trying to load an object while expecting json?

Ubuntu 14.04
node v5.11.1
npm 3.8.6

Who's on First data was downloaded from github and is 26GB.

**whosonfirst-data folder**
```
ubuntu@pelias-01:/mnt/data/whosonfirst/whosonfirst-data$ ls -l
total 80
-rw-rw-r--  1 ubuntu ubuntu  5078 May 26 23:02 CONTRIBUTING.md
drwxrwxr-x 16 ubuntu ubuntu  4096 May 26 23:07 data
-rw-rw-r--  1 ubuntu ubuntu 10467 May 26 23:02 LICENSE.md
-rw-rw-r--  1 ubuntu ubuntu  4347 May 26 23:02 Makefile
drwxrwxr-x  2 ubuntu ubuntu 28672 May 26 23:09 meta
-rw-rw-r--  1 ubuntu ubuntu   513 May 26 23:02 README.KNOWN.KNOWNS.md
-rw-rw-r--  1 ubuntu ubuntu 13267 May 26 23:02 README.md
```

**pelias.json**
```
ubuntu@pelias-01:~/openaddresses$ cat ../pelias.json 
{
  "logger": {
    "level": "debug"
  },
  "esclient": {
    "hosts": [{
      "env": "production",
      "protocol": "http",
      "host": "localhost",
      "port": 9200
    }]
  },
  "imports": {
    "openstreetmap": {
      "adminLookup": false,
      "leveldbpath": "/tmp",
      "datapath": "/mnt/data/openstreetmap",
      "import": [{
        "filename": "north-america.osm.pbf"
      }]
    },
        "openaddresses": {
            "datapath": "/mnt/data/openaddresses",
            "files": []
        },
    "whosonfirst": {
      "datapath": "/mnt/data/whosonfirst/whosonfirst-data"
    }
  }
}
```

**Error log**
```
ubuntu@pelias-01:~/openaddresses$ node import.js --admin-values
2016-05-27T19:28:04.652Z - info: [openaddresses] Setting up admin value lookup stream.
2016-05-27T19:28:04.844Z - info: [openaddresses] Importing 1 files.
2016-05-27T19:28:05.456Z - info: [admin-lookup:worker] 39 disputed record ids loaded in 0.278 secs
2016-05-27T19:28:05.459Z - info: [admin-lookup:worker] disputed finished building FeatureCollection in 0.283 secs
2016-05-27T19:28:05.467Z - info: [admin-lookup:worker] Done loading disputed
2016-05-27T19:28:05.467Z - info: [admin-lookup:worker] disputed finished loading 39 features in 0.291 secs
2016-05-27T19:28:05.746Z - info: [admin-lookup:worker] 5 borough record ids loaded in 0.216 secs
2016-05-27T19:28:05.749Z - info: [admin-lookup:worker] borough finished building FeatureCollection in 0.221 secs
2016-05-27T19:28:05.751Z - info: [admin-lookup:worker] Done loading borough
2016-05-27T19:28:05.751Z - info: [admin-lookup:worker] borough finished loading 5 features in 0.223 secs
2016-05-27T19:28:05.900Z - info: [openaddresses] Creating read stream for: /mnt/data/openaddresses/Independence.csv
2016-05-27T19:28:05.989Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'borough' } 'Worker borough just told me it loaded!'
2016-05-27T19:28:05.990Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'disputed' } 'Worker disputed just told me it loaded!'
2016-05-27T19:28:06.059Z - info: [admin-lookup:worker] 350 macrocounty record ids loaded in 0.675 secs
2016-05-27T19:28:06.062Z - info: [admin-lookup:worker] macrocounty finished building FeatureCollection in 0.68 secs
2016-05-27T19:28:06.071Z - info: [admin-lookup:worker] Done loading macrocounty
2016-05-27T19:28:06.072Z - info: [admin-lookup:worker] macrocounty finished loading 350 features in 0.69 secs
2016-05-27T19:28:06.107Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'macrocounty' } 'Worker macrocounty just told me it loaded!'
2016-05-27T19:28:06.820Z - info: [admin-lookup:worker] 39 dependency record ids loaded in 0.823 secs
2016-05-27T19:28:06.833Z - info: [admin-lookup:worker] dependency finished building FeatureCollection in 0.839 secs
2016-05-27T19:28:06.885Z - info: [admin-lookup:worker] Done loading dependency
2016-05-27T19:28:06.888Z - info: [admin-lookup:worker] dependency finished loading 39 features in 0.894 secs
2016-05-27T19:28:06.890Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'dependency' } 'Worker dependency just told me it loaded!'
2016-05-27T19:28:10.735Z - info: [admin-lookup:worker] 83 macroregion record ids loaded in 4.612 secs
2016-05-27T19:28:10.757Z - info: [admin-lookup:worker] macroregion finished building FeatureCollection in 4.635 secs
2016-05-27T19:28:10.824Z - info: [admin-lookup:worker] Done loading macroregion
2016-05-27T19:28:10.825Z - info: [admin-lookup:worker] macroregion finished loading 83 features in 4.704 secs
2016-05-27T19:28:10.826Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'macroregion' } 'Worker macroregion just told me it loaded!'
2016-05-27T19:28:15.917Z - verbose: [openaddresses] Number of bad records: 0
events.js:154
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token v
    at Object.parse (native)
    at Through2.<anonymous> (/home/ubuntu/openaddresses/node_modules/pelias-wof-pip-service/src/components/loadJSON.js:18:17)
    at Through2._transform (/home/ubuntu/openaddresses/node_modules/through2-map/index.js:19:18)
    at Through2.Transform._read (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Through2.Transform._write (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at Through2.Writable.write (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Through2.ondata (/home/ubuntu/openaddresses/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:90:13)
2016-05-27T19:28:25.920Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:28:30.217Z - info: [admin-lookup:worker] 4699 region record ids loaded in 24.961 secs
2016-05-27T19:28:30.220Z - info: [admin-lookup:worker] region finished building FeatureCollection in 24.966 secs
2016-05-27T19:28:30.479Z - info: [admin-lookup:worker] Done loading region
2016-05-27T19:28:30.480Z - info: [admin-lookup:worker] region finished loading 4699 features in 25.226 secs
2016-05-27T19:28:30.483Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'region' } 'Worker region just told me it loaded!'
2016-05-27T19:28:35.927Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:28:45.932Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:28:55.938Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:05.944Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:15.948Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:25.952Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:35.956Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:40.251Z - info: [admin-lookup:worker] 20415 county record ids loaded in 94.373 secs
2016-05-27T19:29:40.255Z - info: [admin-lookup:worker] county finished building FeatureCollection in 94.38 secs
2016-05-27T19:29:40.589Z - info: [admin-lookup:worker] Done loading county
2016-05-27T19:29:40.590Z - info: [admin-lookup:worker] county finished loading 20415 features in 94.715 secs
2016-05-27T19:29:40.592Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'county' } 'Worker county just told me it loaded!'
2016-05-27T19:29:45.962Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:29:55.969Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:05.975Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:15.980Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:25.984Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:35.988Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:45.994Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:30:55.996Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:06.002Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:16.008Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:26.013Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:35.299Z - info: [admin-lookup:worker] 69482 neighbourhood record ids loaded in 209.148 secs
2016-05-27T19:31:35.302Z - info: [admin-lookup:worker] neighbourhood finished building FeatureCollection in 209.154 secs
2016-05-27T19:31:35.723Z - info: [admin-lookup:worker] Done loading neighbourhood
2016-05-27T19:31:35.724Z - info: [admin-lookup:worker] neighbourhood finished loading 69482 features in 209.576 secs
2016-05-27T19:31:35.725Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'neighbourhood' } 'Worker neighbourhood just told me it loaded!'
2016-05-27T19:31:36.014Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:46.021Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:31:56.024Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:06.029Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:16.032Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:26.036Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:36.040Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:46.045Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:32:50.994Z - info: [admin-lookup:worker] 106627 localadmin record ids loaded in 285.024 secs
2016-05-27T19:32:50.998Z - info: [admin-lookup:worker] localadmin finished building FeatureCollection in 285.031 secs
2016-05-27T19:32:51.553Z - info: [admin-lookup:worker] Done loading localadmin
2016-05-27T19:32:51.553Z - info: [admin-lookup:worker] localadmin finished loading 106627 features in 285.587 secs
2016-05-27T19:32:51.555Z - info: [wof-pip-service:master] { type: 'loaded', layer: 'localadmin' } 'Worker localadmin just told me it loaded!'
2016-05-27T19:32:56.053Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:06.058Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:16.065Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:26.074Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:36.081Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:46.088Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:33:56.095Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:34:06.102Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:34:16.109Z - verbose: [openaddresses] Number of bad records: 0
2016-05-27T19:34:26.116Z - verbose: [openaddresses] Number of bad records: 0
```

**Comment by orangejulius** [comment]
Hey @brianjcollins,
Thanks for reporting this! I think this is fixed by https://github.com/pelias/wof-pip-service/pull/33 which was merged, but there was not an NPM package made with the changes until just now. If NPM works as I expect you should be able to fix this problem with an `npm update`. However if that doesn't work, let me know if `rm -rf node_modules && npm install` (aka the NPM version of turning it off and back on again) fixes it. :bulb:

**Comment by brianjcollins** [comment]
I think that will do it, it at least points me in the right direction!  It is still failing overall to import any of the records, however, I can see why now.


`2016-05-28T11:25:10.055Z - error: [wof-pip-service:loadJSON] exception occured parsing /mnt/data/whosonfirst/whosonfirst-data//data/856/333/45/85633345.geojson: SyntaxError: Unexpected token v`

It's in the who's on first readme, but I didn't apparently pay much attention to it.  What's happening is, that particular file, 85633345.geojson is oversized.  So even though my cloned data was 100% complete, they use git LFS for files over 100MB.  Which that file is.  So when the import is expecting JSON, it's seeing it as malformed, since it is.  It only contains the metadata required to download the real file using git lfs.

Unfortunately, I'm stuck at that point.

```
ubuntu@pelias-01:/mnt/data/whosonfirst/whosonfirst-data$ git lfs fetch
Fetching master
Git LFS: (0 of 1 files) 0 B / 114.67 MB                                                                                                                              
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
```

**Comment by orangejulius** [comment]
Ouch, that's unfortunate. @thisisaaronland will want to know that whosonfirst-data has hit its LFS limit.

The good news is there are [WOF bundles](https://whosonfirst.mapzen.com/bundles/), simple tar files of all the same data (minus the management of git of course - which can be good or bad). If you just want the data you'll be just as happy using those.

**Comment by brianjcollins** [comment]
Ahh there we go!  I was able to use the bundles to download the proper geojson file I needed.  Everything imported as planned!

Oh, also I wasn't able to use `npm update` I had to delete the node_modules directory and reinstall.

Thanks for your help, and the project.  It's very cool!
